name: Deploy to cPanel

on:
  push:
    branches:
      - production

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Install dependencies
      run: |
        composer install --no-progress --prefer-dist --optimize-autoloader
        npm install
        npm run prod

    - name: Deploy to cPanel
      env:
        CPANEL_HOST: ${{ secrets.CPANEL_HOST }}
        CPANEL_USER: ${{ secrets.CPANEL_USER }}
        CPANEL_PASSWORD: ${{ secrets.CPANEL_PASSWORD }}
        DEST_DIR: /path/to/your/project/on/cpanel
      run: |
        rsync -avz --exclude '.git*' --exclude 'node_modules' --exclude 'vendor' ./ $CPANEL_USER@$CPANEL_HOST:$DEST_DIR
        ssh $CPANEL_USER@$CPANEL_HOST 'cd $DEST_DIR && composer install --no-dev && php artisan migrate --force'
